<a href="https://colab.research.google.com/github/Akshithkumarreddy/ML_AI_CLASSE/blob/main/2_Inspect_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
print(arr)

[[1 2 3]
 [4 5 6]]


### inspect general information of an array

In [10]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x3464910
byteorder:  little
byteswap:  False
type: int64
None


### inspect the data type of an array

In [11]:
print(arr.dtype)

int64


### inspect the dimension of an array

In [12]:
print(arr.shape)

(2, 3)


### inspect length of an array

In [14]:
print(arr)
print(len(arr))

[[1 2 3]
 [4 5 6]]
2


### inspect the number of dimensions of an array

In [15]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [16]:
print(arr.size)

6


### inspect the number of bytes of each element in an array

In [17]:
print(arr.itemsize)

8


### inspect the memory size of an array (in byte)

In [19]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48
