<a href="https://colab.research.google.com/github/Akshithkumarreddy/ML_AI_CLASSE/blob/main/3_Sampling_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

### set seed

In [14]:
np.random.seed(123)

### set random state which is independent from the global seed

In [15]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [16]:
# generate a random scalar
print(np.random.rand())

0.6964691855978616


In [25]:
# generate a 1-D array
print(np.random.rand(3))

[0.32295891 0.36178866 0.22826323]


In [30]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.08319499 0.76368284 0.24366637]
 [0.19422296 0.57245696 0.09571252]
 [0.88532683 0.62724897 0.72341636]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [34]:
print(np.random.randn(3,3))

[[ 0.18103513  1.17786194 -0.33501076]
 [ 1.03111446 -1.08456791 -1.36347154]
 [ 0.37940061 -0.37917643  0.64205469]]


### generate an array of random integers in a given interval [low, high)

In [43]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 5 6]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [50]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.55147061 0.56232065 0.43148605 0.36056504 0.51866089 0.41165849
 0.02945699 0.05396756 0.11702945 0.62847058]
[0.42945962 0.12910116 0.37163583 0.7740198  0.74238635 0.06753657
 0.70682921 0.31981183 0.98050237 0.15655755]
[0.2042632  0.4837251  0.47783535 0.06774467 0.52412791 0.82371056
 0.42333087 0.58119017 0.75228461 0.39554438]
[0.46583576 0.79078103 0.80486584 0.16677372 0.77011669 0.4693528
 0.92542108 0.33079165 0.30494205 0.4842225 ]


### generate a random sample from a given 1-D array

In [51]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[2 1 1 1 1 0 1 1 1 0]


In [52]:
print(np.random.choice(3, 10))

[1 2 2 2 0 1 2 0 2 1]


In [53]:
print(np.random.choice([1,2,3], 10))

[3 1 2 2 1 1 2 3 2 2]


### shuffle an array in place

In [62]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
np.random.shuffle(arr)
print(arr)

[4 6 2 8 9 0 3 1 5 7]


### generate a permutation of an array

In [72]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [7 4 5 0 9 2 3 8 1 6]
