<a href="https://colab.research.google.com/github/Akshithkumarreddy/ML_AI_CLASSE/blob/main/5_Slicing_%26_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array(range(100)).reshape((10,10))
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### select an element by row and column indices

In [3]:
print(arr[5][5])
print(arr[5,5])

55
55


### indexing with slicing

In [4]:
print(arr[1:3,4:6])
# print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [6]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
print(arr)
# print(arr[0])
print(arr[1])
# equivalent to arr[0,:,:,:]
# print(arr[0, ...])

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [7]:
# [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
arr = np.array([[[[0,1],[2,3]], [[4,5],[6,7]]], [[[8,9],[10,11]], [[12,13], [14,15]]]])
print(arr.shape)
print(arr[0,0,0,1])

(2, 2, 2, 2)
1


### assign a scalar to a slice by broadcasting

In [9]:
arr = np.array(range(100)).reshape((10,10))
print(arr)
arr[1:3,:] = 100    # or simply arr[1:3]
print(arr)
arr[:,8:] = 100
print(arr)
arr[-1] = 100
print(arr)
arr[-1,:-1]=200
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[  0   1   2   3   4   5   6   7   8   9]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]]
[[  0   1   2   3   4   5   6   7 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37 100 100]
 [ 40  41  42  43  44  45  46  47 100 100]
 [ 50  51  52  53  54  

### boolean indexing

In [10]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
bools = np.array([True, True, False, False, True])
print(arr1[bools])
print(arr1[bools,bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]
[ 0  6 24]


In [12]:
import numpy as np

# Define diagonal elements
diag_values = np.array([True, True, False, True, False])

# Create a 5x5 matrix filled with False
bool_matrix = np.zeros((5, 5), dtype=bool)
print(bool_matrix)

# Assign the diagonal values
np.fill_diagonal(bool_matrix, diag_values)

# Print the boolean matrix
print(bool_matrix)


[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[ True False False False False]
 [False  True False False False]
 [False False False False False]
 [False False False  True False]
 [False False False False False]]


In [ ]:
[[ True  False False False False]
 [ False  True False False False]
 [ False False False False False]
 [ False False False  True False]
 [ False False False False False]]


In [ ]:
Diagonal Elements = [TT,TT,FF,TT,FF]

In [13]:
# negate the condition
print(arr1[~bools])

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])
print(arr2)
print(arr2<2, arr2>4)
print(arr1[(arr2<2) | (arr2>4)])
# multiple conditions
# print(arr1[(arr2<2) | (arr2>4)])

[1 2 3 4 5]
[ True False False False False] [False False False False  True]
[10 50]


### fancy indexing

In [15]:
arr = np.random.rand(10,10)
print(arr)

[[0.42912721 0.758127   0.48664043 0.39697135 0.59772436 0.33918478
  0.53801213 0.02560409 0.69478963 0.70800802]
 [0.90651713 0.56408398 0.04073214 0.2467336  0.22816131 0.54039766
  0.83328128 0.11794445 0.71961422 0.66193661]
 [0.69176131 0.05780576 0.86460552 0.59022448 0.17900575 0.16141424
  0.73251805 0.66107377 0.90020914 0.02327592]
 [0.80173454 0.59968934 0.64334621 0.70473888 0.71455996 0.93006557
  0.07761832 0.12867511 0.06355745 0.88874999]
 [0.49503356 0.32860031 0.55493751 0.77454843 0.33334976 0.52554899
  0.67535594 0.97946173 0.45798195 0.72498371]
 [0.50729169 0.05847085 0.56263057 0.44993155 0.59237151 0.36981995
  0.23647934 0.34604711 0.2035229  0.0154174 ]
 [0.19542832 0.35904786 0.12754353 0.58595554 0.48911682 0.28585209
  0.82628172 0.6443959  0.03442769 0.39427145]
 [0.95512394 0.35691595 0.65412495 0.42298107 0.26171116 0.45952605
  0.23749553 0.58035032 0.95367068 0.60779684]
 [0.09767815 0.48345131 0.53635679 0.67495303 0.93263166 0.5069645
  0.95649699 

In [16]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])

[0.70473888 0.04073214 0.05780576]


In [17]:
print(arr[[3,1,2]][:,2])

[0.64334621 0.04073214 0.86460552]


In [18]:
# select rows 3,1,2 and columns 6,4,8
print(arr[[3,1,2]][:, [6,4,8]])

[[0.07761832 0.71455996 0.06355745]
 [0.83328128 0.22816131 0.71961422]
 [0.73251805 0.17900575 0.90020914]]


In [19]:
arr = np.array(range(100)).reshape((10,10))
print(arr)
print(arr[[1,3,5,7,9]][:,[2,5]])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[12 15]
 [32 35]
 [52 55]
 [72 75]
 [92 95]]


### dimension inference

In [21]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((16,-1))
print(arr.shape)

(16, 1)


### find elements/indices by conditions

In [22]:
arr = np.arange(16).reshape(4,4)

In [23]:
print(arr>5)
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15]


In [24]:
# return values based on conditions
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [25]:
# find the indices of the elements on conditions
print(np.argwhere(~(arr>5)))

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]]
