<a href="https://colab.research.google.com/github/Akshithkumarreddy/ML_AI_CLASSE/blob/main/6_Sort_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array(range(24,-1,-1)).reshape(5,5)
print(arr)

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


### sort an array along a specified axis

In [3]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))
print(arr)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]
[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [4]:
# sort along the row in place
print(np.sort(arr,axis=0))
print(arr)
print(arr.sort(axis=0))

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]
[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
None


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
# sort along the column in place
arr.sort(axis=1)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### compute the indices that would sort an array along a specified axis

In [7]:
arr = np.random.randint(1,100,(5,5))
print(arr)

[[85 97 97  3 25]
 [95 31 81 29 95]
 [14 88 89 91 38]
 [76 88 55 98 98]
 [68  9 96 50  1]]


In [8]:
# along the row
print(np.argsort(arr, axis=0))

[[2 4 3 0 4]
 [4 1 1 1 0]
 [3 2 2 4 2]
 [0 3 4 2 1]
 [1 0 0 3 3]]


In [9]:
# along the column
print(np.argsort(arr, axis=1))

[[3 4 0 1 2]
 [3 1 2 0 4]
 [0 4 1 2 3]
 [2 0 1 3 4]
 [4 1 3 0 2]]


In [10]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[24  3 21 10  4  8  6 14 23 17 20 15  7  0 11 16 12 13  9  5 22  2  1 18
 19]
