<a href="https://colab.research.google.com/github/Akshithkumarreddy/ML_AI_CLASSE/blob/main/Numpy_Pandas_Quiz_Answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Which of the following statements correctly creates a NumPy array with an explicit unsigned integer data type?
#A) np.array([1, 2, 3], dtype=np. uint8) B) np.array([1, 2, 3], dtype='uint') C) np.array([1, 2, 3], dtype=np.int64) D) np.array([1, 2, 3], dtype=np.int8)

import numpy as np
a = np.array([1, 2, 3], dtype='uint') #array([1, 2, 3], dtype=uint64)
b = np.array([1, 2, 3], dtype=np. uint8) #array([1, 2, 3], dtype=uint8)

print(a,b)

[1 2 3] [1 2 3]


In [10]:
#What will be the shape of arr = np.zeros((3,4,5), dtype=int)?
#A) (3, 4, 5) B) (5, 4, 3) C) (4, 5, 3) D) Error due to invalid syntax

arr = np.zeros((3,4,5), dtype=int)
print(arr)
arr.shape

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


(3, 4, 5)

In [11]:
#What does arr[arr > 10] return if arr = np.array([5, 15, 25, 35])?
#A) [15, 25, 35] B) [5] C) array([15, 25, 35]) D) [25, 35]

arr = np.array([5, 15, 25, 35])
arr[arr > 10] # array([15, 25, 35])

array([15, 25, 35])

In [12]:
#What will np.sort(np.array([3, 1, 4, 1, 5, 9])) return?
#A) [1, 1, 3, 4, 5, 9] B) [3, 1, 4, 1, 5, 9] C) [9, 5, 4, 3, 1, 1] D) [1, 3, 4, 1, 5, 9]

np.sort(np.array([3, 1, 4, 1, 5, 9])) #array([1, 1, 3, 4, 5, 9])

array([1, 1, 3, 4, 5, 9])

In [ ]:
#How do you perform element-wise multiplication between two NumPy arrays a and b?
#A) np.dot (a, b) B) a @b C) a b D) np. multiply (a, b)

#answer : D

#A) np.dot(a, b): This performs a dot product, not element-wise multiplication.
#B) a @ b: This operator performs matrix multiplication (also called the matrix product), not element-wise multiplication.
#C) a b: This syntax is invalid in Python and won't work.
#D) np.multiply(a, b): This performs element-wise multiplication between arrays a and b.

In [13]:
#What will be the output of np. floor (np.array([2.3, 3.7, -2.8, -3.1]))?
 #A)[2, 3, -2, -3] B) [2, 4, -3, -4] C) [2.0, 3.0, 3.0, -4.0] D) [2, 3, -3, -4]

np. floor (np.array([2.3, 3.7, -2.8, -3.1])) #array([ 2.,  3., -3., -4.])

array([ 2.,  3., -3., -4.])

In [ ]:
#What is the difference between np.cumsum(arr) and np. cumprod (arr)?
#A) np.cumsum computes the sum cumulatively, np. cumprod computes the cumulative product
#B) np.cumsum returns the total sum, np.cumprod returns the total product
#C) np.cumsum finds the sum, np.cumprod finds the min
#D) Both return the same result for arrays containing only 1s

#answer : A

#np.cumsum(arr): This function computes the cumulative sum of the elements along a given axis.
#It returns an array where each element is the sum of all previous elements up to that index.

#np.cumprod(arr): This function computes the cumulative product of the elements along a given axis.
#It returns an array where each element is the product of all previous elements up to that index.

In [ ]:
#What does df.loc [1, 'Column1'] return in a Pandas DataFrame?
#A) The value in row index 1 and column 'Column1' B) The entire row at index 1 C) The entire column 'Column1' D) The last row of the DataFrame

Answer : A

In [ ]:
#What does np.argmax (arr) return?
#A) The index of the maximum value in arr B) The maximum value in arr C) A sorted version of arr D) The index of the minimum value in arr

#answer : A

In [19]:
#What does np.random.choice([10, 20, 30, 40], size=3, replace=False) do?
#A) Randomly selects 3 elements from the list [10, 20, 30, 40] without replacement B) Selects the first 3 elements from the list
#C) Selects 3 elements with replacement D) Always returns [10, 20, 30]

np.random.choice([10, 20, 30, 40], size=3, replace=False)

#answer : A

array([40, 10, 30])

In [20]:
#What will np.ravel (np.array([[1, 2, 3], [4, 5, 6]])) return?
#A) [1, 2, 3, 4, 5, 6]
#B) [[1, 2, 3], [4, 5, 6]]
#C) (1, 2, 3, 4, 5, 6)
#D) [(1, 2, 3), (4, 5, 6)]

np.ravel (np.array([[1, 2, 3], [4, 5, 6]])) #array([1, 2, 3, 4, 5, 6])

#The ravel() function in NumPy is used to flatten an array, returning a 1D array. It creates a flattened view of the original array whenever possible.
#If the view is not possible, it returns a copy.

array([1, 2, 3, 4, 5, 6])

In [ ]:
#What does df.pivot (index='A', columns= 'B', values='C') do?
#A) Reshapes the DataFrame with unique values from 'A' as rows and 'B' as columns B) Replaces NaN values in column 'C'
#C) Removes duplicates from column 'A'
#D) Groups by 'A' and computes the sum of 'C'

#Answer : A

#The pivot() function in Pandas is used to reshape the DataFrame. Specifically, it creates a new DataFrame where:

#The values from column 'A' will become the row labels.
#The values from column 'B' will become the column labels.
#The values from column 'C' will fill the table at the intersections of the unique values from 'A' and 'B'.

In [21]:
#What will be the shape of np.array([[1,2,3], [4, 5, 6]]).reshape(-1, 1)?
#A) (6, 1)
#B) (1, 6)
#C) (2, 3)
#D) (3, 2)

np.array([[1,2,3], [4, 5, 6]]).reshape(-1, 1) # (6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
#What does np.argmin (np.array([[3, 2, 1], [6, 5, 4]]), axis=1) return?
#A) [2, 2]
#B) [0, 1]
#C) [1, 2]
#D) [2, 2, 2]

#ANSWER : A

In [26]:
#What will np.array([1, 2, 3]) + np.array([[4], [5], [6]]) return?
#A) A 3x3 matrix with element-wise broadcasting
#B) A 1D array
#C) A single number representing the sum
#D) Error due to shape mismatch

np.array([1, 2, 3]) + np.array([[4], [5], [6]])

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
#Which of the following functions can be used to compute the correlation coefficient of a NumPy array?
#A) np.corrcoef() this is used for correlation coefficient
#B) np.cov()
#C) np.correlation ()
#D) np. covariance()

In [ ]:
#What is the correct way to find the rolling mean of a column in Pandas?
#A) df['col'].rolling (3).mean()
#B) df['col'].mean (rolling=3)
#C) df.rolling_mean('col', 3)
#D) df['col'].window (3).mean()

#answer : A , The rolling() function in Pandas creates a rolling window of the specified size (in this case, 3),
#             and then you can apply functions like mean(), sum(), or other aggregation functions to this rolling window.

In [27]:
#What does np.isin (np.array([1, 2, 3, 4]), [2, 3, 5]) return?
#A) [False, True, True, False]
#B) [True, False, False, True]
#C) [1, 2, 3]
#D) [True, True, False, False]

np.isin (np.array([1, 2, 3, 4]), [2, 3, 5]) #array([False,  True,  True, False])

array([False,  True,  True, False])

In [ ]:
#What does df ['col' ].nunique () return?
#A) The number of unique values in 'col'  - This is correct
#B) The count of all values in 'col'
#C) The number of NaN values in 'col'
#D) The mode of 'col'


In [29]:
#What does np.setdiff1d (np.array([1, 2, 3, 4]), np.array([2, 4, 6])) return?
#A) [1, 3]
#B) [2, 4]
#C) [1, 2, 3, 4]
#D) [6]

np.setdiff1d (np.array([1, 2, 3, 4]), np.array([2, 4, 6])) #array([1, 3])

array([1, 3])

In [30]:
#What does np. flatnonzero (np.array([[0, 1], [2, 0]])) return?
#A) [1, 2]
#B) [0, 1, 2, 3]
#C) [1, 2]
#D) [1, 3]

np. flatnonzero (np.array([[0, 1], [2, 0]])) #array([1, 2])

array([1, 2])

In [31]:
#What is the output of np. diag (np.array([[1, 2], [3, 4]]))?
#A) [1, 4]
#B) [[1, 0], [0, 4]]
#C) [2, 3]
#D) [[1, 2], [3, 4]]

np. diag (np.array([[1, 2], [3, 4]])) #array([1, 4])

array([1, 4])

In [32]:
#What will np.repeat (np.array([1, 2, 3]), 2) return?
#A) [1, 1, 2, 2, 3, 3]
#B) [1, 2, 3, 1, 2, 3]
#C) [[1, 1], [2, 2], [3, 3]]
#D) [1, 2, 3]

np.repeat (np.array([1, 2, 3]), 2) #array([1, 1, 2, 2, 3, 3])

array([1, 1, 2, 2, 3, 3])

In [ ]:
#What does df.drop_duplicates (subset=['A'], keep='first') do in Pandas?
#A) Removes duplicate rows based on column 'A', keeping the first occurrence B) Drops column 'A' from the DataFrame
#C) Removes the first occurrence of duplicates in column 'A'
#D) Returns an error if 'A' has NaN values

#Answer ; A

In [ ]:
#Which function in NumPy can be used to generate an array of evenly spaced values on a logarithmic scale?
#A) np.logspace() this is correct
#B) np. linspace()
#C) np.geomspace()
#D) np.expspace()

In [ ]:
#What does df.iloc[:, [1, 3]].values return?
#A) All rows from columns at index positions 1 and 3 - this is correct
#B) The entire DataFrame
#C) A list of column names
#D) The first and third rows


In [34]:
#What does np.random. permutation (5) return?
#A) A shuffled array of [0, 1, 2, 3, 4] -
#B) A random integer between 0 and 5
#C) A 5x5 identity matrix
#D) A sorted array of [0, 1, 2, 3, 4]

np.random. permutation (5) #array([4, 2, 3, 0, 1])

array([4, 2, 3, 0, 1])

In [36]:
#What will be the shape of np.array([[1, 2], [3, 4]]).T?
#A) (2, 2)
#B) (4, 1)
#C) (1, 4)
#D) (2, 4)

A = np.array([[1, 2], [3, 4]]).T
A.shape # (2, 2)

(2, 2)

In [37]:
#What is the output of np. round (np.array([1.45, 2.55, 3.65]), decimals=1)?
#A) [1.4, 2.6, 3.6]
#B) [1.5, 2.5, 3.6]
#C) [1.5, 2.6, 3.6]
#D) [1.4, 2.5, 3.6]

np. round (np.array([1.45, 2.55, 3.65]), decimals=1) #array([1.4, 2.6, 3.6])

array([1.4, 2.6, 3.6])

In [ ]:
#What does df.fillna (df.mean()) do?
#A) Replaces NaN values with the mean of their respective columns - This is correct answer
#B) Removes all NaN values
#C) Returns the mean of all columns
#D) Fills NaN values with zero


In [38]:
#What does np.clip (np.array([-5, 0, 10, 15]), 0, 10) return?
#A) [0, 0, 10, 10]
#B) [-5, 0, 10, 15]
#C) [0, 0, 10, 15]
#D) [0, 0, 10, 10]

np.clip (np.array([-5, 0, 10, 15]), 0, 10) #array([ 0,  0, 10, 10])

#he clip() function in NumPy is used to limit the values in an array within a specified range.
#Any values in the array that are below a given minimum will be set to the minimum
#, and any values that are above a given maximum will be set to the maximum.

#numpy.clip(a, a_min, a_max, out=None)

array([ 0,  0, 10, 10])

In [ ]:
#What does df.set_index('Column1') do in a Pandas DataFrame?
#A) Sets 'Column1' as the index of the DataFrame
#B) Deletes 'Column1' from the DataFrame
#C) Sorts the DataFrame based on 'Column1'
#D) Returns an error if 'Column1' contains NaN values

#answer - A

In [39]:
#What does np.expand_dims (np.array([1,2,3]), axis=0). shape return?
#A) (1, 3)
#B) (3, 1)
#C) (1, 1, 3)
#D) (3,)

np.expand_dims (np.array([1,2,3]), axis=0). shape #(1, 3)

(1, 3)

In [ ]:
#What does df [df['Column1'].notnull()] return?
#A) Rows where 'Column1' is not null
#B) Rows where 'Column1' contains NaN values
#C) A sorted DataFrame
#D) Only the 'Column 1' column

#answer - a

In [40]:
#What will np.concatenate([np.array([1,2]), np.array([3,4])], axis=0) return?
#A) [1, 2, 3, 4]
#B) [[1, 2], [3, 4]]
#C) [1, 3, 2, 4]
#D) Error due to shape mismatch

np.concatenate([np.array([1,2]), np.array([3,4])], axis=0) #array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
#Which function returns the index positions of non-zero elements in a NumPy array?
#A) np. nonzero() - This is correct answer
#B) np.where()
#C) np. nonzero_indices()
#D) np.index_nonzero()

In [41]:
#What does np. linalg.inv (np. eye (3)) return?
#A) A 3x3 identity matrix
#B) A zero matrix
#C) An error
#D) The inverse of a randomly generated 3x3 matrix

np. linalg.inv (np. eye (3)) # answer - A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Which of the following functions can be used to stack NumPy arrays vertically?
#A) np.vstack() - This is correct answer
#B) np.concatenate() with axis=0
#C) np.hstack()
#D) np.column_stack()

In [ ]:
#What is the output of df.sort_values (by= [ 'Column1', 'Column2'], ascending [True, False])?
#A) The DataFrame sorted by 'Column1' in ascending order and 'Column2' in descending order
#B) The DataFrame sorted by 'Column2' in ascending order and 'Column1' in descending order
#C) The DataFrame sorted only by 'Column1'
#D) The DataFrame sorted only by 'Column2'

#answer - A

In [ ]:
#What does np.cov (np.array([[1,2,3], [4, 5, 6]])) compute?
#A) The covariance matrix of the two arrays
#B) The correlation matrix of the two arrays
#C) The dot product of the arrays
#D) The element-wise multiplication of the arrays

#answeer -= A

In [ ]:
#What does np.tril(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])) return?
#A) A lower triangular matrix of the given array
#B) An upper triangular matrix of the given array
#C) A transposed version of the array
#D) The determinant of the matrix

#answer - A

#np.tril() returns the lower triangular matrix of a given square matrix.
#This function sets all elements above the main diagonal to zero, leaving the elements on and below the diagonal intact.

In [ ]:
#What does df.query("A > 5 and B < 10") do?
#A) Selects rows where column A is greater than 5 and column B is less than 10
#B) Creates a new column A with values greater than 5
#C) Filters out NaN values from columns A and B
#D) Returns an error if A or B contain strings

#Answer - A

In [ ]:
#What will np.meshgrid (np.array([1,2,3]), np.array([4,5])) return?
#A) Two coordinate matrices from input arrays
#B) The element-wise sum of two arrays
#C) A 3D array of shape (3,2)
#D) A single 2D array of shape (3,2)

#Answer - A) Two coordinate matrices from input arrays.

#The function np.meshgrid() creates coordinate grids from two input arrays. It returns two 2D arrays (coordinate matrices)
#that correspond to the grid of coordinates formed by the combinations of the elements from the input arrays.

In [ ]:
#What does df.corr() compute?
#A) Pearson correlation coefficients between numeric columns
#B) Covariance matrix of numeric columns
#C) The difference between max and min values in each column
#D) The mean squared error of numeric columns

#Answer - A

In [42]:
#What is the result of np.diff (np.array([10, 15, 25, 40]))?
#A) [5, 10, 15]
#B) [10, 15, 25, 40]
#C) [5, 10, 15, 25]
#D) [15, 25, 40]

np.diff (np.array([10, 15, 25, 40])) #array([ 5, 10, 15])

array([ 5, 10, 15])

In [ ]:
#What does df.rolling (window=3). mean () do in Pandas?
#A) Computes the moving average with a window size of 3
#B) Shifts all values down by 3 rows
#C) Computes the cumulative sum of the column
#D) Returns an error if window size exceeds the DataFrame size

# answer : A) Computes the moving average with a window size of 3.


#df.rolling(window=3).mean() computes the rolling (or moving) mean with a window size of 3 for each column in the DataFrame.
#The rolling() function creates a "rolling" view over the DataFrame, allowing you to apply various aggregation functions (such as mean, sum, etc.)
#over a specified window of rows.

In [ ]:
#What does np.bincount (np.array([1,2,1,2,1,3])) return?
#A) A count of occurrences of each integer in the array
#B) A sorted version of the array
#C) A boolean mask of elements greater than 2
#D) The sum of all values in the array

#Answer : A) A count of occurrences of each integer in the array

#he function np.bincount() counts the occurrences of each non-negative integer value in a NumPy array.
#It returns an array where the index corresponds to the integer, and the value at that index is the count of occurrences of that integer in the input array.

In [ ]:
#What will df.iloc[:, -1] return?
#A) All rows with all columns except the last one
#B) The last column of the DataFrame
#C) A DataFrame with every second column removed
#D) Only the last row of the DataFrame

#answer - B) The last column of the DataFrame.

In [ ]:
#What is the purpose of np. cumsum(np.array([1,2,3,4]))?
#A) Computes the cumulative sum of the array
#B) Finds the sum of the array
#C) Returns an array of ones with the same shape D) Computes the cumulative product

#Answer : A


In [ ]:
#What does df.pct_change () compute?
#A) Percentage change between consecutive rows
#B) The mean percentage of all values in the DataFrame
#C) The percentage of missing values in the DataFrame
#D) The difference between min and max values in the DataFrame

#  Answer : A